### ISSUE TITLE
remove vocal from song

### ISSUE THREAD

**Issue by 404000** [tsurumeso/vocal-remover#32]
I tried some songs,The singer's voice is not removed from these songs
make your vocal remover remove all vocals from all songs

**Comment by aufr33** [comment]
The standard model was trained in just 170 songs (pairs). You must train your model yourself. I used 350 songs and already got much better results.

In any case, today there is no such AI that would clear any songs from vocals.

**Comment by 404000** [comment]
tell me how train your own model

**Comment by aufr33** [comment]
> 
> 
> tell me how train your own model

Read the README file. It is very long and difficult to assemble a good dataset. You need to prepare a pair of instrumental and mix. I downloaded multitracks and mixed every song through the audio editing software.

**Comment by 404000** [comment]
I did not understand explain to me using a video

**Comment by TRvlvr** [comment]
Datasets can take a LONG time to assemble.

-  The dataset must be comprised of pairs consisting of official instrumentals & official mixes.
-  The pairs MUST be perfectly aligned! Also, the spectrograms must match up evenly, and the pairs should have the same volume, otherwise, training will not be effective and you'll have to start over.
-  I've found in my own experiences that not every official studio instrumental will align with its official mix counterpart. If it doesn't align, that means it's NOT usable! I can't stress this enough. What I found was if the timing is slightly different between the 2 tracks, it will render it impossible to align. If you don't know how to align tracks, know that it's the exact same process people use to extract vocals using an instrumental and mix (vocal extraction isn't necessary for this. Although, knowing if they can be using this classic method, with MINIMAL to no artifacts, makes for a good litmus test for rather or not the pair is a good candidate for training. There are tons of tutorials on YouTube that show how to perfectly align tracks. Also, you can bypass some of that work by making an instrumental and mix out of multitrack stems. Using multi-tracks to create pairs is the most concrete way to build a perfectly aligned dataset. However, carefully aligning wave-forms and spectrograms for instrumentals and mixes is a pretty good way too because you can easily expand your dataset.

**Comment by aufr33** [comment]
> 
> I've found in my own experiences that not every official studio instrumental will align with its official mix counterpart. 

By the way, it is not necessary to use official instrumental. I also used "homemade" instrumentals + choral singing. And even voice samples from the Voyager Golden Records + classical music.

**Comment by TRvlvr** [comment]
> > I've found in my own experiences that not every official studio instrumental will align with its official mix counterpart.
> 
> By the way, it is not necessary to use only official instrumentals. I also used "homemade" instrumentals + choral singing. And even voice samples from the Voyager Golden Records + classical music.

You can do that as well, but I haven't had much luck using homemade instrumentals. The issue being that any lingering vocals (even background vocals) will compromise the effectiveness of the model. I find it's better to train the AI on instrumentals with absolutely no vocals in them at all. 

If background vocals are needed for karaoke, it's best to plug them in after conversions.

**Comment by bascurtiz** [comment]
@aufr33 
@TRvlvr 

You can also download all the beatport stems (15000+) which are 2 mins previews of full tracks, split up in 4 stems in decent quality, using this python script:
https://gist.github.com/kylemcdonald/e20ec59273e78d0075bd71a1d08f4c41

Alter line 12: `total_tracks = 4106` to `total_tracks = 15400`
Alter line 34 :  `print 'Error: ' + r.status` to `print('Error:' + r.status)`
Make sure Python 3.x is installed.

I also have a The Largest Multitrack Music Collection Ever! 2013 66.3GB torrent d/led, which contains 1385 studio ripped multitracks tracks. Let me know if interested.

**Comment by aufr33** [comment]
> The issue being that any lingering vocals (even background vocals) will compromise the effectiveness of the model.

No, I meant that I used a pair of "clean music and my own mix". 

Although, an _additional_ model trained on instrumentals with backing vocals is a good idea. I have already tried and got funny results. My "backing" model really keeps the backing vocals, but it works worse.

But I still do not understand what to do with vocal chops [](https://youtu.be/_6PPKDUY5Gw?t=126) and vinyl scratches. After all, this is part of the music, but, on the other hand, it is a human voice. This contradicts each other. So far I'm cutting out all the dubious sounds, just in case.



> Alter line 34 : `print 'Error: ' + r.status` to `print('Error:' + r.status)`
> Make sure Python 3.x is installed.

My python version is Python 3.7.4, but I still get this error.

**Comment by bascurtiz** [comment]
@aufr33 
Since Spleeter uses a 16khz filter, I don't think 96khz will affect it as much.
See also: https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-models-up-to-16khz

![image](https://user-images.githubusercontent.com/34075088/86334560-ac73df00-bc4d-11ea-8802-309ce2da3fc1.png)

**Comment by aufr33** [comment]
It is true, many people do not hear above 16 kHz. But this is not the only deterioration in quality. There are also losses at medium frequencies, smoothing transients, etc. Personally, I would use such mp3 files only in a small amount to expand the dataset.

**Comment by 404000** [comment]
What's in a file baseline .pth in vocal remover

**Comment by aufr33** [comment]
I also want to note that the use of some songs in the dataset (for example, Gorillaz - Feel Good Inc) led to inadequate results. I had no choice but to remove them and start the learning process again.
